{% set name = "rdflib-shim" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdflib_shim-{{ version }}.tar.gz
  sha256: d955d11e2986aab42b6830ca56ac6bc9c893abd1d049a161c6de2f1b99d4fc0d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pbr
    - pip
  run:
    - python >={{ python_min }}
    - rdflib >=5.0.0
    - rdflib-jsonld ==0.6.1

test:
  imports:
    - rdflib_shim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://hsolbrig.github.io/rdflib-shim
  summary: Shim for rdflib 5 and 6 incompatibilities
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jfy133
